### ISSUE TITLE
Updating a partially downloaded question

### ISSUE THREAD

**Issue by DSuveges** [DSuveges/gyik_scraper#23]
If at some later time, the database needs to be re-freshed, we can fetch new questions and avoid downloading questions that are already in the database however there might be new answers. How to fetch only those questions that got new answers?

**Logic**:

- For each question ID on a page, retrieve the number of answers.
- For each question ID retrieve the  number of answers submitted by other than the OP.
- If these numbers are different, but the question ID is in the DB do the following:
- Remove row with question id from the questions table
- Remove rows with question id from the answers table.
- Remove rows with question id from the question keyword table.
- Then process question.

**Tasks**:

- [ ] Add functionality to return number of answers from the parserd html
- [ ] Add sql to return the number of answers submitted by other than the OP
- [ ] Add sql to drop question by question id
- [ ] Add sql to drop answers by question id
- [ ] Add sql to drop keyword link by question id
- [ ] Add logic to

**Comment by DSuveges** [comment]
The problem is, deleting the question is not allowed as there are dependent tables in the database. However, there's an option to use cascading delete that performs an automatic delete from all tables where the foreign key found. The only caveat is that it has to be [specified upon database creation](https://www.techonthenet.com/sqlite/foreign_keys/foreign_delete.php#:~:text=A%20foreign%20key%20with%20cascade,in%20a%20CREATE%20TABLE%20statement.).
